// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParishApi.Entity;

namespace ParishApi.Migrations
{
    [DbContext(typeof(ParishContext))]
    [Migration("20211119045615_SecondMigration")]
    partial class SecondMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ParishApi.Models.MST_Documents", b =>
                {
                    b.Property<int>("docid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("createddate")
                        .HasColumnType("datetime2");

                    b.Property<string>("doccomment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("docdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("docname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("docurl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fileextension")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("docid");

                    b.ToTable("MST_Documents");
                });

            modelBuilder.Entity("ParishApi.Models.Member", b =>
                {
                    b.Property<int>("memberid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("accoundcode")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("bloodgroup")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("city")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("country")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime?>("dob")
                        .HasColumnType("datetime2");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("firstname")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<string>("homeparish")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("homephone")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<bool?>("isactive")
                        .HasColumnType("bit");

                    b.Property<bool?>("isapproved")
                        .HasColumnType("bit");

                    b.Property<bool?>("isemailnotification")
                        .HasColumnType("bit");

                    b.Property<bool?>("ismarried")
                        .HasColumnType("bit");

                    b.Property<bool?>("issmsnotification")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("joiningdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("lastname")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("membercode")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("middlename")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("mobileno")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("occupation")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("permanentaddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pincode")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("presentaddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("profileimage")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<string>("qualification")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("state")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("street")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<decimal>("subscriptionamount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("weddingdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("workphone")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.HasKey("memberid");

                    b.ToTable("Member");
                });

            modelBuilder.Entity("ParishApi.Models.MemberFamilyDetail", b =>
                {
                    b.Property<int>("memberfamilyid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("address1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bloodgroup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("emailid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("isapproved")
                        .HasColumnType("bit");

                    b.Property<int?>("memberid")
                        .HasColumnType("int");

                    b.Property<string>("relation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("reldob")
                        .HasColumnType("datetime2");

                    b.Property<string>("relgender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("relmobileno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("relname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("state")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("memberfamilyid");

                    b.ToTable("MemberFamilyDetail");
                });

            modelBuilder.Entity("ParishApi.Models.UserLogin", b =>
                {
                    b.Property<string>("usercode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("lastloggedin")
                        .HasColumnType("datetime2");

                    b.Property<string>("password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("username")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("usertype")
                        .HasColumnType("int");

                    b.HasKey("usercode");

                    b.ToTable("UserLogin");
                });
#pragma warning restore 612, 618
        }
    }
}
